name: build wsh-backend

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  actions: read
  packages: write

concurrency:
  group: wsh-backend-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Git checkout for Github repository workspace
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'zulu'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Setup QEMU for multiarch builds
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker build
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.SECRET_TOKEN }}

      - name: Verify Java
        run: java -version

      - name: Build with Gradle Wrapper
        run: ./gradlew --no-daemon server:publishImage
        env:
          GITHUB_USERNAME: ${{ github.repository_owner }} # token name
          DOCKER_SECRET: ${{ secrets.SECRET_TOKEN }} # token secret (password)

